name: Nightly Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Zip build directory
        run: zip -r gauntlet-nightly.zip build/

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d-%H%M')"

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "gauntlet-nightly.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: nightly-${{ steps.date.outputs.date }}
          name: Gauntlet Nightly ${{ steps.date.outputs.date }}
          body: |
            ⚠️ Gauntlet Nightly - Unstable Release ⚠️

            This is a nightly build generated from the latest code. It is provided for users who are fine with bugs and want to have the latest features. It may contain bugs and incomplete features. Use it at your own risk.

            For the latest stable release, please look at the [Releases](https://github.com/libcord-tech/gauntlet/releases/latest) page.
          draft: false
          prerelease: true
